data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    path: '/Home/daniel094144/LAS/LibriSpeech'
    name: 'LibriSpeech'
    dev_split: ['dev-clean']
    test_split: ['test-clean']
    bucketing: False
    batch_size: 1
src:
  config: '/Home/daniel094144/End-to-end-ASR-Pytorch/config/librispeech_asr_best.yaml'
  ckpt: '/Home/daniel094144/End-to-end-ASR-Pytorch/ckpt/ori_vgg/best_att_dev-clean.pth'

decode:
  ctc_weight: 0
  beam_size: 8
  # vocab_candidate: 12
  min_len_ratio: 0.01
  max_len_ratio: 0.3
  #lm_config: '/data/storage/harry/End-to-end-ASR-Pytorch/config/librispeech_lm.yaml'
  #lm_path: '/data/storage/harry/E2E_ASR/ckpt/RNNLM_LS100_TEST_0/best_ppx.pth'
  #lm_weight: 0.3